baseurl = "https://noahkernis.com/"
title = "noahkernis.com"
theme = "hugo-theme-console"
languageCode = "en-us"

[params]
  	# Cutting off the page title to two chars for mobile (console-demo -> co)
  	titleCutting = false
    copyright = "All The Rights - All Of Time - All To Noah Kernis"

	[[params.navlinks]]
		name = "about/"
		url = "about/"

	[[params.navlinks]]
		name = "projects/"
		url = "projects/"

	[[params.navlinks]]
		name = "generic_error/"
		url = "generic_error/"

	[[params.navlinks]]
		name = "contact/"
		url = "contact/"


[privacy]
	[privacy.disqus]
		disable = false

	[privacy.googleAnalytics]
		disable = false
		anonymizeIP = true
		respectDoNotTrack = true
		useSessionStorage = true

	[privacy.instagram]
		disable = false
		simple = true
		disableInlineCSS = true

	[privacy.twitter]
		disable = false
		enableDNT = true
		simple = true
		disableInlineCSS = true

	[privacy.vimeo]
		disable = false
		simple = true

	[privacy.youtube]
		disable = false
		privacyEnhanced = true